<?php

namespace AppBundle\Repository;

/**
 * ContentItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContentItemRepository extends \Doctrine\ORM\EntityRepository
{
}
