AppBundle\Entity\ContentItem:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            type: integer
        gaPath:
            expose: true
            type: string
        publicUrl:
            expose: true
            type: string
        title:
            expose: true
            type: string
        publishedDate:
            expose: true
            type: DateTime
        author:
            expose: true
            type: string
        visits:
            expose: true
            type: integer
        bounceRate:
            expose: true
            type: float
        avgTimeOnPage:
            expose: true
            type: float
        visitsPoints:
            expose: true
            type: integer
        bounceRatePoints:
            expose: true
            type: integer
        avgTimeOnPagePoints:
            expose: true
            type: integer
        totalPoints:
            access_type: public_method
            read_only: true
            expose: true
            type: integer
